### ISSUE TITLE
[Key Generation page] Link to download CLI releases

### ISSUE THREAD

**Issue by Battenfield** [ethereum/eth2.0-deposit#138]
Several windows users have left feedback about the [Deposit-CLI](https://github.com/ethereum/eth2.0-deposit-cli) permission issues. A new release of the CLI has fixed this and it has been discussed to display a link to the repo's GH releases page tracked here [#github/eth2.0-deposit-cli/67](https://github.com/ethereum/eth2.0-deposit-cli/issues/67).

@hwwhww Can you provide context on how this link should be represented visually? Is running the executable the preferred way for all machines, or just Windows?

Is there any impact on section 3 content?

Shall the link go above the code emulator? Mention the preferred method?

Should it link out to the general [releases page ](https://github.com/ethereum/eth2.0-deposit-cli/releases/)or the specific [0.2.1 tagged release](https://github.com/ethereum/eth2.0-deposit-cli/releases/tag/v0.2.1)?

![Screen Shot 2020-07-28 at 5 03 24 PM](https://user-images.githubusercontent.com/7051522/88741440-80386a80-d0f4-11ea-8243-c857c4cd0b28.png)

**Comment by hwwhww** [comment]
@Battenfield 

Learn from the recent feedback, I think the workflow could be changed to:
1. Provide (i) binary executable file and (ii) `virtualenv` options: we concerned that using `virtualenv` requires the user to download extra packages and learn about how to use it, but now I feel it's just too difficult to make everyone's environment clean and no conflicts.
    - List binary file as option 1 since its instruction is shorter.
2. Remove `git` installation: the git users can download it via git, but for the non-technical users, they can just download it from the GitHub website.
3. Remove `deposit.sh` one since it doesn't fit for all Windows users.
4. Add some "hints" to the instruction

I'm proposing the instruction revisions (feel free to overhaul the wording):
- Windows users: https://hackmd.io/MPLCgqZDSbWX4PcW2-6LMA
- For macOS or Linux users: https://hackmd.io/IoMvowW0SmeBZGOmIE3sJg
    - the only the status-quo content and “Generate deposit keys using the Ethereum Foundation deposit tool” command are different.

It's a bit similar to the deposit-cli README.md steps. IMHO we have to combine header 3. and 4. if we provide two options.

---

> Is there any impact on section 3 content?

See above

> Shall the link go above the code emulator? Mention the preferred method?

See above, I'd say set it to "option 1".

> Should it link out to the general releases page or the specific 0.2.1 tagged release?

Good question, I'd say general releases page would be fine since we should not change the commands in the future. I noted "the latest deposit-cli release" on the above proposals.

----

Thanks! :)

**Comment by CarlBeek** [comment]
Closed via #146
