### ISSUE TITLE
App crashes on Mobile and safari - Bigint error

### ISSUE THREAD

**Issue by Battenfield** [ethereum/eth2.0-deposit#87]
#83 created a new app crashing bug on certain browsers
- Chrome Mobile
- Safari (desktop and mobile)

<img width="1320" alt="Screen Shot 2020-06-04 at 5 25 27 PM" src="https://user-images.githubusercontent.com/7051522/83823263-6ea08c80-a688-11ea-8c06-9153910588f8.png">

**Comment by CarlBeek** [comment]
As it turns out, IE, Safari, and Safari-iOS all do not support BigInts. (Although support has been added to the Dev-build of Safari.) BigInts are a part of ES2020, but clearly there isn't universal support yet. Unfortunately it cannot be transpiled as it uses `+`, `-`, `<<` etc as symbols for the associated methods. The particular syntax that it is not happy with here is `1n` which is shorthand for `BigInt(1)`. Unfortunately, this is not easy to fix because even ignoring this issue, it will still fail at runtime when `BigInt` objects are used.

One solution is to swap out `BigInt`s for the [JSBI](https://github.com/GoogleChromeLabs/jsbi) library's implementation which is a native JS version of the same thing (but uses incompatible syntax). It should be noted that this problem is not something we induced, but via a dependency we use for checking the merkle root ([@chainsafe's persistent merkle root](https://github.com/ChainSafe/persistent-merkle-tree)).

Possible solutions:

* Don't support IE & Safari Entirely
* Change the syntax (remove `1n`) in persistent-merkle and just not verify the root in Safari/IE (note that the `DepositMessage` is still verified by the deposit contract, but there is scope for loss of funds
* Move over to [JSBI](https://github.com/GoogleChromeLabs/jsbi)

**Comment by wemeetagain** [comment]
Hiya, chainsafer here, just stumbled upon this issue.

I think if we use the `BigInt()` syntax instead of bigint literals, in the persistent-merkle-tree dependency, that you should be able to verify the deposit roots here w/o an issue. The persistent-merkle-tree code is only activated when operating on full merkle-tree-backed objects, whereas here we're just using javascript objects. The hashTreeRoot implementation operating on javascript objects doesn't involve gindex calculations or anything else that we're using bigints for, so I don't think we will hit any runtime errors calculating the merkle root.

One other thing that would need to change is the use of `BigIntUintType` for the amount.
One solution would be to use the `NumberUintType`, which will only start overflowing after 3.2M+ Ether (with accounting in gwei), well beyond the practical limit for a single deposit.
Another solution, we could implement another Uint type using JSBI, BN.js, etc. that can handle the full range of uint64 values w/o using bigint.

**Comment by wemeetagain** [comment]
We've released v0.6.6 of `@chainsafe/ssz` w/o bigint literals in it or its dependencies.

**Comment by CarlBeek** [comment]
Thanks for cutting a new release, @wemeetagain!

I've implemented the changes in the [carl_SSZ_066](https://github.com/ethereum/eth2.0-deposit/blob/carl_SSZ_066), but I seem to be hitting a BigInt call somewhere deep within SSZ. Would you mind talking a look? Specifically the problem occurs in [this line](https://github.com/ethereum/eth2.0-deposit/blob/carl_SSZ_066/src/utils/SSZ.ts#L80) where  Safari throws `ReferenceError: Can't find variable: Bigint`

**Comment by wemeetagain** [comment]
Ok, we released v0.6.7, which no longer uses BigInt in serialization/merkleization of numbers.

I tested locally against your branch w/ the update linked in; no BigInts detected at runtime :1234: :bomb:  

`@chainsafe/ssz` still uses BigInt for certain other operations (eg: `fromJson`), but for yalls current usage here, hopefully should be good to go.

**Comment by CarlBeek** [comment]
Thanks very much for cutting a new release so quickly and for making sure that there were no `BigInt` calls in the critical path, @wemeetagain!

I've bumped SSZ in #88, and I added range checks on the deposit amount so the SSZ encoding should never fail due to needing `BigInt`s. :)
