### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-deposit#91]
### Issue

1. Eth2 spec `v0.11.x` is not compatible with `v0.12.x` due to BLS signature. To support [Altona testnet](https://github.com/goerli/altona/blob/master/altona/README.md), both the launchpad (this repo) and [deposit-cli](https://github.com/ethereum/eth2.0-deposit-cli) have to upgrade to `v0.12.x` compatible.
2. It's difficult to sync the version of the launchpad and `deposit-cli` now: the instructions currently ask the user to download `https://github.com/ethereum/eth2.0-deposit-cli.git` `master` branch.

### How to solve it

- [x] 1. **[deposit-cli]**: Cut a release of the current `deposit-cli` master, and make it clear that it's in development.
- [x] 2. **[launchpad]**: Make launchpad point to the new `deposit-cli` release branch.
    1. Update `README.md`.
    2. Parameterize https://github.com/ethereum/eth2.0-deposit-cli.git (https://github.com/ethereum/eth2.0-deposit/blob/0d03f61b870c1f0adfdbe2115f52d389738888cd/src/pages/GenerateKeys/LinuxInstructions.tsx#L26) and update all instruction files.
- [ ] 3. **[launchpad]**: Merge `dev` to `master` and cut a `v0.11.x` release of the launchpad

And then we can merge the `v0.12.x` PRs to `dev` branch, and cut a new release for Altona testnet.

@georgeweiler @Battenfield @CarlBeek what do you think?

**Comment by CarlBeek** [comment]
Incase this wasn't made clear by out of band communications with @hwwhww, and @Battenfield, I think this is a sane approach to solving this problem.

**Comment by CarlBeek** [comment]
I just cut [a release](https://github.com/ethereum/eth2.0-deposit-cli/releases/tag/v0.0.0) of the `deposit cli` for v0.11.x. 🎉

Due to the way this repo has been developed, the v0.12.x changes have been intermingled heavily with the other changes, and in my opinion, it is not worth cherry picking commits to come up with a v0.11.x compliant version. As such, I think we should just move forward onto v0.12.x and make that the initial release.
